env:
  node: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:node/recommended
  - plugin:prettier/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - node
  - security
  - prettier
rules:
  prettier/prettier:
    - error
    - singleQuote: true
      trailingComma: 'all'
      printWidth: 80
      tabWidth: 2
  no-console: off
  no-process-exit: error
  node/no-unsupported-features/es-syntax: off
  node/no-unpublished-require: off
  node/no-missing-import: error
  node/no-extraneous-import: error
  security/detect-non-literal-fs-filename: warn
  security/detect-eval-with-expression: error
